In [3]:
#Nominal Ohe >> Binary vectors for each category

In [4]:
#Single, married, in a relationship
#single> [1,0,0]
#married > [0,1,0]
#separated > [0,0,1]

In [5]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [21]:
df=pd.DataFrame({'status': ['single','Married','single','Relationship','Married','single' ]})

In [22]:
df

status
0        single
1       Married
2        single
3  Relationship
4       Married
5        single

In [23]:
encoder=OneHotEncoder()
encoder

OneHotEncoder()

In [24]:
encoder.fit(df[['status']])

OneHotEncoder()

In [25]:
encoded=encoder.fit_transform(df[['status']]).toarray()

In [26]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [27]:
encoder.get_feature_names_out()

array(['status_Married', 'status_Relationship', 'status_single'],
      dtype=object)

In [28]:
pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

status_Married  status_Relationship  status_single
0             0.0                  0.0            1.0
1             1.0                  0.0            0.0
2             0.0                  0.0            1.0
3             0.0                  1.0            0.0
4             1.0                  0.0            0.0
5             0.0                  0.0            1.0

In [30]:
#New Data>> Single

In [32]:
encoder.transform([['single']]).toarray()

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [33]:
encoder.transform([['Married']]).toarray()

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [36]:
df_encoder=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [37]:
df_encoder

status_Married  status_Relationship  status_single
0             0.0                  0.0            1.0
1             1.0                  0.0            0.0
2             0.0                  0.0            1.0
3             0.0                  1.0            0.0
4             1.0                  0.0            0.0
5             0.0                  0.0            1.0

In [35]:
df

status
0        single
1       Married
2        single
3  Relationship
4       Married
5        single

In [39]:
final_df=pd.concat([df,df_encoder],axis=1)

In [40]:
final_df

status  status_Married  status_Relationship  status_single
0        single             0.0                  0.0            1.0
1       Married             1.0                  0.0            0.0
2        single             0.0                  0.0            1.0
3  Relationship             0.0                  1.0            0.0
4       Married             1.0                  0.0            0.0
5        single             0.0                  0.0            1.0

In [43]:
final_df.drop(['status','status_Married'],axis=1 ,inplace=True)

In [44]:
final_df

status_Relationship  status_single
0                  0.0            1.0
1                  0.0            0.0
2                  0.0            1.0
3                  1.0            0.0
4                  0.0            0.0
5                  0.0            1.0

In [45]:
df

status
0        single
1       Married
2        single
3  Relationship
4       Married
5        single

In [50]:
pd.get_dummies(df[['status']])

status_Married  status_Relationship  status_single
0               0                    0              1
1               1                    0              0
2               0                    0              1
3               0                    1              0
4               1                    0              0
5               0                    0              1

In [51]:
pd.get_dummies(df['status'])

Married  Relationship  single
0        0             0       1
1        1             0       0
2        0             0       1
3        0             1       0
4        1             0       0
5        0             0       1

In [52]:
pd.get_dummies(df['status'],drop_first=True)

Relationship  single
0             0       1
1             0       0
2             0       1
3             1       0
4             0       0
5             0       1

In [57]:
#Using Pandas
pd.get_dummies(df['status'],drop_first=True)

Relationship  single
0             0       1
1             0       0
2             0       1
3             1       0
4             0       0
5             0       1

In [60]:
pd.get_dummies(df['status'],drop_first=True)

Relationship  single
0             0       1
1             0       0
2             0       1
3             1       0
4             0       0
5             0       1

In [61]:
#Internal homework

In [148]:
import seaborn as sns
df=sns.load_dataset('tips')

In [156]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [161]:
encoder=OneHotEncoder()

In [162]:
encoder

OneHotEncoder()

AttributeError: 'DataFrame' object has no attribute 'encoder'

In [164]:
encoded1=encoder.fit_transform(df[['time']]).toarray()

In [165]:
encoded1

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [154]:
df['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [166]:
encoder.get_feature_names_out()

array(['time_Dinner', 'time_Lunch'], dtype=object)

In [168]:
df_encoder1=pd.DataFrame(encoded1,columns=encoder.get_feature_names_out())

In [169]:
df_encoder1

time_Dinner  time_Lunch
0            1.0         0.0
1            1.0         0.0
2            1.0         0.0
3            1.0         0.0
4            1.0         0.0
..           ...         ...
239          1.0         0.0
240          1.0         0.0
241          1.0         0.0
242          1.0         0.0
243          1.0         0.0

[244 rows x 2 columns]

In [65]:
#Label Encoding>>> Assign Unique label to the Each of the Category

In [66]:
df

status
0        single
1       Married
2        single
3  Relationship
4       Married
5        single

In [68]:
from sklearn.preprocessing import LabelEncoder

In [70]:
label_encoder=LabelEncoder()


In [73]:
label_encoder.fit_transform(['status'])

array([0], dtype=int64)

In [75]:
label_encoder.fit_transform(df[['status']])

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 1, 0, 2])

In [76]:
df

status
0        single
1       Married
2        single
3  Relationship
4       Married
5        single

In [77]:
#Ordinal Encoding

In [79]:
#highschool>>1
#graduate >> 2
#PG >>3

In [85]:
from sklearn.preprocessing import OrdinalEncoder

df1= pd.DataFrame({"qualification": ["HS","PG","GR","HS","PHD","HS","PG"]})

In [86]:
df1

qualification
0            HS
1            PG
2            GR
3            HS
4           PHD
5            HS
6            PG

In [87]:
encoder=OrdinalEncoder(categories =[["HS","GR","PG","PHD"]])

In [89]:
encoder.fit_transform(df1[['qualification']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.]])

In [90]:
df1

qualification
0            HS
1            PG
2            GR
3            HS
4           PHD
5            HS
6            PG

In [92]:
df1.qualification.value_counts()

HS     3
PG     2
GR     1
PHD    1
Name: qualification, dtype: int64

In [93]:
#Target guided OrdinaL Encoding
#Relation with Target variables
#A lot of uniquer categories
#Replace with mean and median 

In [96]:
df=pd.DataFrame({'time':['lunch','breakfast','dinner','lunch','breakfast','dinner','lunch','breakfast','dinner'],
                 'total_bill':[120,120,40,150,160,130,40,150,160] })

In [97]:
df

time  total_bill
0      lunch         120
1  breakfast         120
2     dinner          40
3      lunch         150
4  breakfast         160
5     dinner         130
6      lunch          40
7  breakfast         150
8     dinner         160

In [100]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [101]:
mean_price

{'breakfast': 143.33333333333334, 'dinner': 110.0, 'lunch': 103.33333333333333}

In [104]:
df['time_target_encoded']=df['time'].map(mean_price)

In [105]:
df['time_target_encoded']

0    103.333333
1    143.333333
2    110.000000
3    103.333333
4    143.333333
5    110.000000
6    103.333333
7    143.333333
8    110.000000
Name: time_target_encoded, dtype: float64

In [106]:
df

time  total_bill  time_target_encoded
0      lunch         120           103.333333
1  breakfast         120           143.333333
2     dinner          40           110.000000
3      lunch         150           103.333333
4  breakfast         160           143.333333
5     dinner         130           110.000000
6      lunch          40           103.333333
7  breakfast         150           143.333333
8     dinner         160           110.000000

In [102]:
df.groupby('time')['total_bill'].sum()

time
breakfast    430
dinner       330
lunch        310
Name: total_bill, dtype: int64

In [108]:
#Internal Homework

In [112]:
import seaborn as sns
df2=sns.load_dataset('tips')

In [113]:
df2

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [117]:
mean_total_bill= df2.groupby('time')['total_bill'].mean().to_dict()

In [118]:
mean_total_bill

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [135]:
df2.time.value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [133]:
df2['time_target_encode']=df2['time'].map(mean_total_bill)

In [134]:
df2['time_target_encode']

C:\Users\shubh\anaconda3\lib\site-packages\IPython\lib\pretty.py:700: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  output = repr(obj)


0      20.797159
1      20.797159
2      20.797159
3      20.797159
4      20.797159
         ...    
239    20.797159
240    20.797159
241    20.797159
242    20.797159
243    20.797159
Name: time_target_encode, Length: 244, dtype: category
Categories (2, float64): [17.168676, 20.797159]

In [136]:
df2

total_bill   tip     sex smoker   day    time  size time_target_encode
0         16.99  1.01  Female     No   Sun  Dinner     2          20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3          20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3          20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2          20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4          20.797159
..          ...   ...     ...    ...   ...     ...   ...                ...
239       29.03  5.92    Male     No   Sat  Dinner     3          20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2          20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2          20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2          20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2          20.797159

[244 rows x 8 columns]

In [138]:
df2['time_target_encode'].value_counts()

20.79715909090909     176
17.168676470588235     68
Name: time_target_encode, dtype: int64